# MNIST Using FeedForward Neural Network

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from tensorflow.keras.datasets import mnist

In [3]:
df=mnist.load_data()

In [4]:
len(df)

2

In [5]:
len(df[0])

2

In [6]:
len(df[1])

2

In [7]:
len(df[0][0])

60000

In [8]:
len(df[0][1])

60000

In [9]:
df[0][0].shape

(60000, 28, 28)

In [10]:
df[0][1].shape

(60000,)

In [11]:
df[1][0].shape

(10000, 28, 28)

In [12]:
df[1][1].shape

(10000,)

In [13]:
(X_train,y_train),(X_test,y_test)=df

In [14]:
X_train.shape

(60000, 28, 28)

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten

In [16]:
# X_train= X_train.reshape(-1,784)
# X_test=X_test.reshape(-1,784)

In [17]:
#X_train = (X_train / 255.0) 
#X_test = (X_test / 255.0) 

In [18]:
X_train.shape

(60000, 28, 28)

In [19]:
model=Sequential()
model.add(Flatten())

In [20]:
model.add(Dense(64,activation='relu',input_shape=(784,)))

In [21]:
model.add(Dense(32,activation='relu'))

In [22]:
model.add(Dense(10,activation='softmax'))

In [23]:
model.compile(optimizer = 'adam', loss='categorical_crossentropy',metrics=['accuracy'])

In [24]:
from tensorflow.keras.utils import to_categorical
model.fit(X_train,to_categorical(y_train),epochs=2)

Epoch 1/2
1875/1875 [==============================] - 2s 1ms/step - loss: 1.4562 - accuracy: 0.6077
Epoch 2/2
1875/1875 [==============================] - 2s 1ms/step - loss: 0.5138 - accuracy: 0.8653


In [25]:
model.evaluate(X_test,to_categorical(y_test))

313/313 [==============================] - 0s 779us/step - loss: 0.3993 - accuracy: 0.9031


[0.39929670095443726, 0.9031000137329102]

In [26]:
 np.argmax(model.predict(X_train[:9]), axis=1) 

array([3, 0, 9, 1, 9, 2, 1, 3, 1], dtype=int64)

In [27]:
y_train[:9]

array([5, 0, 4, 1, 9, 2, 1, 3, 1], dtype=uint8)

In [28]:
from sklearn.metrics import confusion_matrix

In [29]:
confusion_matrix(y_train,np.argmax(model.predict(X_train),axis=1))

array([[5767,    0,   10,    0,    7,    9,   57,    0,   73,    0],
       [   0, 6510,   26,   26,    4,   19,   10,    3,  143,    1],
       [  55,    8, 5316,  128,   37,   29,  118,   17,  248,    2],
       [  24,    3,  107, 5266,    0,  442,   14,   40,  222,   13],
       [   9,    2,    2,    0, 5405,   12,  106,    1,   75,  230],
       [ 119,    6,    9,  341,   17, 4051,   87,    1,  750,   40],
       [  73,    1,    0,    0,   28,   12, 5720,    0,   84,    0],
       [   6,   11,   63,   57,   46,   19,    3, 5645,  156,  259],
       [ 144,   34,   55,   33,    6,  163,   35,    2, 5341,   38],
       [  20,    5,    1,   22,  104,  109,    2,   52,  202, 5432]],
      dtype=int64)

In [30]:
y_train.shape

(60000,)

In [32]:
X_train.shape

(60000, 28, 28)

In [33]:
model.predict(X_train).shape

(60000, 10)